<template>
	<div class="loadingio-spinner-dual-ball-vyoyund2d3m"><div class="ldio-7kud5he3d2k">
	<div></div><div></div><div></div>
	</div></div>
</template>

<script>
	export default {
		name: 'LoadingB' // 定义的组件名称 使用时写法：loading-d
	}
</script>

<style scoped>
	@keyframes ldio-7kud5he3d2k-o {
	    0%    { opacity: 1; transform: translate(0 0) }
	   49.99% { opacity: 1; transform: translate(80px,0) }
	   50%    { opacity: 0; transform: translate(80px,0) }
	  100%    { opacity: 0; transform: translate(0,0) }
	}
	@keyframes ldio-7kud5he3d2k {
	    0% { transform: translate(0,0) }
	   50% { transform: translate(80px,0) }
	  100% { transform: translate(0,0) }
	}
	.ldio-7kud5he3d2k div {
	  position: absolute;
	  width: 80px;
	  height: 80px;
	  border-radius: 50%;
	  top: 60px;
	  left: 20px;
	}
	.ldio-7kud5he3d2k div:nth-child(1) {
	  background: #e90c59;
	  animation: ldio-7kud5he3d2k 1s linear infinite;
	  animation-delay: -0.5s;
	}
	.ldio-7kud5he3d2k div:nth-child(2) {
	  background: #46dff0;
	  animation: ldio-7kud5he3d2k 1s linear infinite;
	  animation-delay: 0s;
	}
	.ldio-7kud5he3d2k div:nth-child(3) {
	  background: #e90c59;
	  animation: ldio-7kud5he3d2k-o 1s linear infinite;
	  animation-delay: -0.5s;
	}
	.loadingio-spinner-dual-ball-vyoyund2d3m {
	  width: 120px;
	  height: 100px;
	  display: flex;
	  overflow: hidden;
	  background: #ffffff;
	  margin: 0 auto;
	}
	.ldio-7kud5he3d2k {
	  width: 100%;
	  height: 100%;
	  position: relative;
	  transform: translateZ(0) scale(0.5);
	  backface-visibility: hidden;
	  transform-origin: 0 0; /* see note above */
	}
	.ldio-7kud5he3d2k div { box-sizing: content-box; }
	/* generated by https://loading.io/ */
</style>
