<template>
	<div class="loadingio-spinner-cube-mdqcyupif8l"><div class="ldio-tygabd0f64g">
<div></div><div></div><div></div><div></div>
</div></div>
</template>

<script>
	export default {
		name: 'LoadingF' // 定义的组件名称 使用时写法：loading-d
	}
</script>

<style scoped>
	@keyframes ldio-tygabd0f64g {
	  0% { transform: scale(1.1500000000000001) }
	  100% { transform: scale(1) }
	}
	.ldio-tygabd0f64g div {
	  position: absolute;
	  width: 80px;
	  height: 80px;
	  top: 13.333333333333336px;
	  left: 13.333333333333336px;
	  background: #6784ec;
	  animation: ldio-tygabd0f64g 1s cubic-bezier(0,0.5,0.5,1) infinite;
	  animation-delay: -0.3s;
	}
	.ldio-tygabd0f64g div:nth-child(2) {
	  top: 13.333333333333336px;
	  left: 106.66666666666666px;
	  background: #d4f460;
	  animation-delay: -0.2s;
	}
	.ldio-tygabd0f64g div:nth-child(3) {
	  top: 106.66666666666666px;
	  left: 13.333333333333336px;
	  background: #d49763;
	  animation-delay: 0s;
	}
	.ldio-tygabd0f64g div:nth-child(4) {
	  top: 106.66666666666666px;
	  left: 106.66666666666666px;
	  background: #f86ab2;
	  animation-delay: -0.1s;
	}
	.loadingio-spinner-cube-mdqcyupif8l {
	  width: 100px;
	  height: 100px;
	  display: inline-block;
	  overflow: hidden;
	  background: #ffffff;
	  margin: 0 auto;
	}
	.ldio-tygabd0f64g {
	  width: 100%;
	  height: 100%;
	  position: relative;
	  transform: translateZ(0) scale(0.5);
	  backface-visibility: hidden;
	  transform-origin: 0 0; /* see note above */
	}
	.ldio-tygabd0f64g div { box-sizing: content-box; }
	/* generated by https://loading.io/ */
</style>
