<template>
	<div class="loadingio-spinner-eclipse-1f85mvlb4ik"><div class="ldio-jlbwfjt8b4">
	<div></div>
	</div></div>
</template>

<script>
	export default {
		name: 'LoadingE' // 定义的组件名称 使用时写法：loading-d
	}
</script>

<style>
	@keyframes ldio-jlbwfjt8b4 {
	  0% { transform: rotate(0deg) }
	  50% { transform: rotate(180deg) }
	  100% { transform: rotate(360deg) }
	}
	.ldio-jlbwfjt8b4 div {
	  position: absolute;
	  animation: ldio-jlbwfjt8b4 1s linear infinite;
	  width: 160px;
	  height: 160px;
	  top: 20px;
	  left: 20px;
	  border-radius: 50%;
	  box-shadow: 0 4px 0 0 #0085ff;
	  transform-origin: 80px 82px;
	}
	.loadingio-spinner-eclipse-1f85mvlb4ik {
	  width: 100px;
	  height: 100px;
	  display: flex;
	  overflow: hidden;
	  background: rgba(NaN, NaN, NaN, 0);
	  margin: 0 auto;
	}
	.ldio-jlbwfjt8b4 {
	  width: 100%;
	  height: 100%;
	  position: relative;
	  transform: translateZ(0) scale(0.5);
	  backface-visibility: hidden;
	  transform-origin: 0 0; /* see note above */
	}
	.ldio-jlbwfjt8b4 div { box-sizing: content-box; }
	/* generated by https://loading.io/ */
</style>
